import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import DetCurveDisplay
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.datasets import fetch_openml
from statistics import mean
from IPython.display import display
import math
import pandas as pd
from sklearn.model_selection import train_test_split
from PolyLayerNeuralNetwork import PolyLayerNetwork

# Ashton
# one hot vector
def one_hot(y, num_classes=10):
    return np.eye(num_classes)[y]

# Zach
# Takes the split parts of the network and the network itself as inputs
# Runs network training on with the training data
# Plots the MSE loss curves and the confusion matrix, along with the balanced accuracy
def train_and_plot_network(network, x, y,):
    # Split the data into training data (x_train) and label (y_train) sets
    # and Test data (x_test) and label (y_test) sets
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

    # Changes training and test labels from a single column to one-hot vectors
    y_train = one_hot(y_train, 10)
    y_test = one_hot(y_test, 10)

    # Call training function on our neural network, giving training data and labels as inputs
    mse_loss_trend_train, mse_loss_trend_cross_validation = network.train(x_train, y_train)

    # Generate an MSE Loss line plot for the training set
    plt.plot(mse_loss_trend_train, color='b', label="MSE Loss - Training Set")

    # Generate an MSE line plot for the CV set
    plt.plot(mse_loss_trend_cross_validation, color='r', label="MSE Loss - CV Set")
    plt.xlabel('Epochs')
    plt.ylabel('MSE Loss')
    plt.title(f"MSE Loss vs Epochs with LR: {network.learning_rate:.2f} & HN: {network.hidden_layers_size}")
    plt.legend()

    # Create an array from the soft score predictions form the Neural Network
    all_y_predicted_soft = []

    # This for loop replaces the previous syntax of:
    #   y = np.apply_along_axis(self.feedforward, 1, data)
    for x, y_true in zip(x_test, y_test):
        input = x.reshape(-1, 1)
        labels = y_true.reshape(-1, 1)
        all_y_predicted_soft.append(network.feedforward(input, labels, train=False))
    all_y_predicted_soft = np.array(all_y_predicted_soft)

    # Use argmax to create hard predictions from the soft predictions (probabilities)
    all_y_predicted_hard = np.argmax(all_y_predicted_soft, axis=1)


    # Gets the index of where the label is
    # From [0 0 0 0 0 0 0 0 0 1]
    # To 9
    y_test_labels = np.argmax(y_test, axis=1)

    # Pass ground-truth labels and predicted hard labels to calculate UAR
    balanced_accuracy = balanced_accuracy_score(y_test_labels, all_y_predicted_hard)

    # Print UAR
    print("Test balanced accuracy: ", balanced_accuracy)

    # Generate confusion matrix from ground-truth labels and hard predicted labels
    cm = confusion_matrix(y_test_labels, all_y_predicted_hard)

    # Display generated confusion matrix
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot()
    plt.title(f'Confusion Matrix For {network.hidden_layers}-NN with:\n '
              f'{network.hidden_layers_size} Neurons per layer & LR = {network.learning_rate:.2f}')
    plt.show()

    plt.show()

    return balanced_accuracy

# Zach
# Creates a 3D graph that shows the balanced accuracy
# Uses the Learning rate and hidden neurons for the x and y-axis
# Based on the graphs from previous projects
def graph_balanced_accuracy(Z):
    peak_learning_rate = 0

    # Code to try to get a 3D graph for looking for the best balanced accuracy
    # based on hidden nuerons and learning rate
    # Our 2-dimensional distribution will be over variables X and Y
    N = 15  # Number of ticks on X, Y axes
    X = np.linspace(0, 15, N)
    Y = np.linspace(10, 310, N)
    X, Y = np.meshgrid(X, Y)


    # Pack X and Y into a single 3-dimensional array
    pos = np.empty(X.shape + (2,))  # size (N, N, 2)
    pos[:, :, 0] = X
    pos[:, :, 1] = Y
    # X, Y = np.meshgrid(X, Y)


    # Adds the information to the contour plot and shows the plot
    plt.contourf(X, Y, Z)
    plt.title("Balanced Accuracy over learning rate and hidden layer size")
    plt.show()

    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(111, projection='3d')

    ax.plot_surface(X, Y, Z, cmap='viridis')

    ax.set_xlim(ax.get_xlim()[::-1])  # reverse X
    ax.set_ylim(ax.get_ylim()[::-1])  # reverse Y

    ax.set_xlabel("Learning Rate")
    ax.set_ylabel("Hidden Layer Neurons")
    ax.set_zlabel("Balanced Accuracy")

    plt.show()

# Zach
# Generated by ChatGPT as another way of the looking at the 3D graph
# Based on the other accuracy graph
def graph_balanced_accuracy_heatmap(Z, hidden_layer_sizes: list[int],
                                    learning_rates: list[float]) -> None:
    peak_learning_rate = 0
    HR = hidden_layer_sizes
    LR = learning_rates
    neurons = (np.arange(hidden_layer_sizes[0], 310, 20))  # 0, 20, 40, 60, 80
    learning_rates = np.arange(0.05, 0.20, 0.01)        # 0.10–0.14 (5 values)


    fig, ax = plt.subplots(figsize=(8, 6))

    im = ax.imshow(Z, cmap='inferno', interpolation='bilinear', origin='lower')

    # Label ticks with real values
    ax.set_xticks(np.arange(len(neurons)))
    ax.set_yticks(np.arange(len(learning_rates)))

    ax.set_xticklabels(neurons)
    ax.set_yticklabels(learning_rates)

    ax.set_xlabel("Hidden Neurons")
    ax.set_ylabel("Learning Rate")
    ax.set_title("Balanced Accuracy Heatmap")

    # Add numbers inside each cell
    for i in range(Z.shape[0]):
        for j in range(Z.shape[1]):
            ax.text(j, i, f"{Z[i, j]:.2f}", ha="center", va="center", color="white")

    fig.colorbar(im, ax=ax, label="Balanced Accuracy")
    plt.show()


# Zach - Modified by Brady
# Iterates over a range of values for the learning rate and hidden neurons
# Graphs a 3D graph for both the LR and hidden nuerons with the balanced accuracy
# Might crash at the end, indexing issues
def peak_balanced_accuracy(x: np.ndarray, y: np.ndarray, hidden_layers: int,
                           hidden_layer_sizes: list[int], learning_rates: list[float],max_epoch: int) -> None:
    max_balanced_accuracy = 0.0
    peak_learning_rate = 0
    peak_neurons = 0

    HL_size = hidden_layer_sizes
    LR = learning_rates

    rows = len(np.arange(LR[0], LR[1], LR[2]))
    cols = len(np.arange(HL_size[0], HL_size[1], HL_size[2]))

    Z = np.zeros((rows, cols))

    iteration = 0
    # Testing Network for performance over learning rate and nuerons per layer
    for i in np.arange(LR[0], LR[1], LR[2]):
        row = 0
        for j in np.arange(HL_size[0], HL_size[1], HL_size[2]):
            col = 0
            print(f"Iteration {iteration}")

            poly_layer_network = PolyLayerNetwork(hidden_layers, int(j), i, max_epoch)
            balanced_accuracy = train_and_plot_network(poly_layer_network, x, y)

            if balanced_accuracy > max_balanced_accuracy:
                max_balanced_accuracy = balanced_accuracy
                peak_learning_rate = i
                peak_neurons = j

            #row = int(i * 100) - int(LR[0] * 100)
            #col = int(j) - int[HL_size[0]]
            Z[row, col] = balanced_accuracy

            row += 1
            col += 1
            iteration += 1

    #graph_balanced_accuracy(Z)

    #graph_balanced_accuracy_heatmap(Z)

    print(
        f"Max balanced accuracy is {max_balanced_accuracy} "
        f"with a learning rate of {peak_learning_rate:.2f} and {peak_neurons} neurons.")

# Zach - Modified by Brady
# Iterates over a range of values for the learning rate
# Graphs the balanced accuracy for each step of the learning rate
def peak_learn_rate(x: np.ndarray, y: np.ndarray, hidden_layers: int,
                    hidden_layers_sizes: int, learning_rates: list[float], max_epoch: int) -> None:
    peak_learning_rate = 0

    HL_size = hidden_layers_sizes
    LR = learning_rates

    balanced_accuracy_trend = []
    iteration = 0
    # Loop for iterating over the range of learning rates
    for i in np.arange(LR[0], LR[1], LR[2]):
        print(f"Iteration {iteration}")
        poly_layer_network = PolyLayerNetwork(hidden_layers, HL_size, i, max_epoch)

        balanced_accuracy = train_and_plot_network(poly_layer_network, x, y)

        balanced_accuracy_trend.append(balanced_accuracy)

        iteration += 1

    # Graphs the balanced accuracy
    x_values = np.arange(LR[0], LR[1], LR[2])
    plt.plot(x_values, balanced_accuracy_trend, color='b', label="Balanced Accuracy")
    plt.xlim(LR[0], LR[1])
    plt.title(f'Balanced Accuracy of {poly_layer_network.hidden_layers}-Layer-NN with:\n'
              f'{poly_layer_network.hidden_layers_size} Neurons per layer & Learning Rate Sweep')
    plt.xlabel('Learning rate')
    plt.ylabel('Balanced Accuracy')
    plt.legend()

    plt.show()

    print(f"With a peak learning rate of {peak_learning_rate:.2f}.")

# Zach - Modified by Brady
# Iterates over a range of values for the hidden neurons in a layer
# Graphs the balanced accuracy for each step of the learning rate
def peak_hidden_layer_neurons(x: np.ndarray, y: np.ndarray, hidden_layers: int,
                              hidden_layers_sizes: list[int], learning_rates: float, max_epoch: int) -> None:
    peak_hidden_neurons = 0

    HL_size = hidden_layers_sizes
    LR = learning_rates

    balanced_accuracy_trend = []
    iteration = 0
    # Loop for iterating over the range of hidden neurons
    for i in np.arange(HL_size[0], HL_size[1], HL_size[2]):
        print(f"Iteration {iteration}")
        poly_layer_network = PolyLayerNetwork(hidden_layers, int(i), learning_rates, max_epoch)

        balanced_accuracy = train_and_plot_network(poly_layer_network, x, y)

        # Adds to the list of the accuracy list for the graph
        balanced_accuracy_trend.append(balanced_accuracy)

        iteration += 1

    # Graphs the balanced accuracy
    hr_range = np.arange(HL_size[0], HL_size[1], HL_size[2])
    plt.plot(hr_range, balanced_accuracy_trend, color='b', label="Balanced Accuracy")
    plt.xlim(HL_size[0], HL_size[1])
    plt.title(f'Balanced Accuracy of {poly_layer_network.hidden_layers}-Layer-NN with\n'
              f'LR = {poly_layer_network.learning_rate:.2f} & Hidden Layer Sweep')
    plt.xlabel('Number of hidden neurons per layer')
    plt.ylabel('Balanced Accuracy')
    plt.legend()

    plt.show()

    print(f"With {peak_hidden_neurons} peak hidden neurons.")
